### ISSUE TITLE
Check before submitting for new DOI

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/privacy-bibliography#21]
@ianschmutte and @larsvilhuber have reviewed multiple layout issues, fixed the #18 CIPSEA issue. Please review before minting new DOI.

**Comment by ianschmutte** [comment]
I've made my edits and sign off.

- I did some very minor edits to the "contributions" section
- edited a few references for proper formatting / capitalization
- one thing: the primary citation by "National Academies of Sciences..." does not render properly. I couldn't easily figure out how to make it work.

**Comment by larsvilhuber** [comment]
National Academies - yes, I remember seeing that, and could not find a solution either.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

e: lars.vilhuber@cornell.edu
p: +1.607-330-5743
v: https://cornell.zoom.us/my/larsvilhuber
w: http://lars.vilhuber.com/ <http://lars.vilhuber.com/>

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________

**Comment by larsvilhuber** [comment]
@ianschmutte used commit ed17e49  to implement his suggestions. But forgot to reference it.

**Comment by larsvilhuber** [comment]
I fixed the National Academies thing @ianschmutte in 61dfc2d
