### ISSUE TITLE
Create keyword tags to facilitate bibliographies on specific topics

### ISSUE THREAD

**Issue by ianschmutte** [labordynamicsinstitute/privacy-bibliography#3]
We want to add keyword tags so the bib file can be filtered (using bib2bib) to create html-formatted bibliographies for specific topics

**Comment by larsvilhuber** [comment]
https://en.wikibooks.org/wiki/LaTeX/Bibliographies_with_biblatex_and_biber#Splitting_into_different_topics

**Comment by ianschmutte** [comment]
CATEGORIES.md is tracking the keyword tags

**Comment by ianschmutte** [comment]
added keywords to all references and did some grooming of the other references

**Comment by ianschmutte** [comment]
This task is finished. Will reopen if there's a call to re-evaluate categories.
