### ISSUE TITLE
Add permanent URL / DOI for every paper in the bib. Create local cache of all PDFs.

### ISSUE THREAD

**Issue by ianschmutte** [labordynamicsinstitute/privacy-bibliography#7]
We need a stable, permanent web location for every reference. We also need a local cache of every PDF.

**Comment by ianschmutte** [comment]
Marshall pretty much finished getting all the URL / DOI. We don't have the PDF cache, but I'm closing this anyway. If we decide we want a PDF cache, we can still create it later.

**Comment by larsvilhuber** [comment]
@ianschmutte  The cleanup by Marshall messed up some rendering. He seems to have added 
`doi = {N/A},`
if a DOI was not available. However, that prevents a URL, if present, to be displayed in some bibliography styles (in particular in the one used for the online reading list).

I have fixed this in dbf7e8b  but it may need to be backported to the full bibliography.
